### ISSUE TITLE
Research and prototype VPN

### ISSUE THREAD

**Issue by ilammy** [apriorit/linux-vpn-2018-winter#2]
- [x] **Исследовать технологии, необходимые для реализации проекта**

    В комментариях следует разместить список технологий. Рядом с каждым пунктом также стоит описать, что это вообще такое и почему следует выбрать именно его.

    Будет плюсом сравнение альтернатив, если они есть.

- [x] **Написать прототип VPN-сервера**

    Это должно быть _простое_ серверное приложение под Linux, которое умеет принимать и пересылать пакеты. Без авторизации клиентов, без шифрования пакетов, со статическими IP-адресами, без поддержки нескольких клиентов, и т. д.

- [x] **Написать прототип VPN-клиента**

    Это должен быть _простой_ сервис под Android, который умеет добавлять VPN на устройство и пересылать пакеты на сервер. Опять же, без шифрования, без сложного GUI, и т. д.

Результаты работы — прототипы — следует разместить в репозитории в отдельных ветках.

**Comment by ilammy** [comment]
@wizir6, @Daria-Vasilyeva, напишите, пожалуйста, в комментариях к этой задаче, какие технологии исследовали, что попробовали, и на чём в итоге остановились для прототипов.

**Comment by Daria-Vasilyeva** [comment]
Прототип Клиента было решено писать на языке Java,  так как он лучше всего подходит для этих целей, ведь основной API к платформе предоставлен в виде Java библиотек. Приложение разрабатывалось в среде Android Studio. В  поиске основного инструмента для создания vpn подключения был перерыт весь интернет, рассмотрено множество аналогов. В конечном итоге выбрали класс VpnService, так как он предоставляет весь базовый инструмент для создания vpn, так же он простой в использовании.

В качестве протокола транспортного уровня рассматривались TCP и UDP протоколы, подробно изучив различия данных протоколов, выбрали UDP, так как он лучше подходит для этой задачи,  в рассмотренных аналогах использовался именно UDP + он работает быстрее TCP, что немаловажно для конечного пользователя.

**Comment by wizir6** [comment]
Для серверной части реализация была на с++. Так как сначала был выбор протокола транспортного уровня, рассматривались множество библиотек для работы с трафиком. В их числе QtNetwork, Tacopie. Последняя включена в стандарт с++11, но подходит только для TCP. Наиболее подходящей оказалась библиотека boost::asio. Позволяет создавать сервера с разными типами протоколов. По данной библиотеке есть удобная документация и книга, где более подробно описываются ее возможности.
