### ISSUE TITLE
Estimate project development

### ISSUE THREAD

**Issue by ilammy** [apriorit/linux-vpn-2018-winter#5]
Нужно спланировать будущую работу по проекту.

План следует оформить в виде списка задач, выполнение которых приведёт проект к успеху. Задачи могут состоять их подзадач. Каждая (под)задача должна быть сформулирована достаточно чётко, чтобы вам было ясно, что конкретно следует сделать для её завершения (например, «Реализовать класс VpnConnectionManager»).

Кроме собственно разбиения на подзадачи необходимо также 1) оценить время, необходимое на выполнение задач, 2) назначить ответственных за выполнение каждой задачи. Каждая задача должна занимать не больше пары дней. У задачи должен быть один человек, ответственный за неё.

Если возникают сложности с оценкой времени, то это скорее всего означает, что или задача слишком крупная (её следует разбить на подзадачи и оценивать уже их), или же она недостаточно хорошо исследована (в этом случае следует оценить время на дополнительное исследование, и хотя бы прикинуть итоговую сложность задачи — типа, вложится в неделю или нет).

План следует разместить здесь. Лучше прямо текстом в комментариях. Можно также в виде проекта MS Project.

**Comment by wizir6** [comment]
https://docs.google.com/document/d/1VVPt3LkJJSfla4eWU-AUuo33TF3j7oYnzkKTj6PNT5A/edit

**Comment by Daria-Vasilyeva** [comment]
![image](https://user-images.githubusercontent.com/36243078/36935566-09745856-1f02-11e8-9f90-7b01e99031e5.png)

**Comment by Daria-Vasilyeva** [comment]
![image](https://user-images.githubusercontent.com/36243078/36935574-1fb3126a-1f02-11e8-95bf-e3deb7907cce.png)

**Comment by ilammy** [comment]
Хм. По части разработки в плане всё более-менее вменяемо. Что несколько смущает — это всего по два-три дня на тестирование и отладку. Я думаю, это займёт существенно больше времени (от недели).
